const STORE_KEY='lcdc-time-v1';
const monthNames=['janvier','février','mars','avril','mai','juin','juillet','août','septembre','octobre','novembre','décembre'];
const shortMonths=['janv.','févr.','mars','avr.','mai','juin','juil.','août','sept.','oct.','nov.','déc.'];
const defaultState={rate:25,farms:[{id:'lcdc',name:'Client principal',town:'Erdre et Loire',color:'#28755b'}],entries:[]};
let state=loadState();let activeMonth=new Date();activeMonth.setDate(1);let selectedDate=isoDate(new Date());let installPrompt;let editingEntryId=null;
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function loadState(){try{return {...defaultState,...JSON.parse(localStorage.getItem(STORE_KEY)||'{}')}}catch{return structuredClone(defaultState)}}
function saveState(){localStorage.setItem(STORE_KEY,JSON.stringify(state));renderAll()}
function isoDate(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function localDate(value){const [y,m,d]=value.split('-').map(Number);return new Date(y,m-1,d)}
function formatDate(value,opts={weekday:'long',day:'numeric',month:'long'}){return localDate(value).toLocaleDateString('fr-FR',opts)}
function decimalHours(s,e){if(!s||!e)return 0;const [sh,sm]=s.split(':').map(Number),[eh,em]=e.split(':').map(Number);return Math.max(0,(eh*60+em-sh*60-sm)/60)}
function hoursFor(e){return Math.max(0,decimalHours(e.morningStart,e.morningEnd)+decimalHours(e.afternoonStart,e.afternoonEnd)-(Number(e.breakMinutes)||0)/60)}
function displayHours(n){const h=Math.floor(n),m=Math.round((n-h)*60);return m?`${h} h ${String(m).padStart(2,'0')}`:`${h} h`}
function monthEntries(){return state.entries.filter(e=>{const d=localDate(e.date);return d.getFullYear()===activeMonth.getFullYear()&&d.getMonth()===activeMonth.getMonth()})}
function getFarm(id){return state.farms.find(f=>f.id===id)||{name:'Exploitation supprimée',town:'',color:'#698094'}}
function euro(n){return new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n)}
function renderStats(){const entries=monthEntries(),hours=entries.reduce((s,e)=>s+hoursFor(e),0),days=new Set(entries.map(e=>e.date)).size;$('#statHours').textContent=displayHours(hours);$('#statRevenue').textContent=euro(hours*state.rate);$('#statDays').textContent=days;$('#statAverage').textContent=displayHours(days?hours/days:0);$('#monthPicker').textContent=`${monthNames[activeMonth.getMonth()][0].toUpperCase()+monthNames[activeMonth.getMonth()].slice(1)} ${activeMonth.getFullYear()}`}
function renderRecent(){const rows=[...state.entries].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4);$('#recentEntries').innerHTML=rows.length?rows.map(e=>{const d=localDate(e.date),f=getFarm(e.farmId),h=hoursFor(e);return `<article class="entry-item"><div class="entry-date"><strong>${d.getDate()}</strong><span>${shortMonths[d.getMonth()]}</span></div><div class="entry-info"><strong>${escapeHtml(f.name)}</strong><small>${escapeHtml(e.notes||formatSchedule(e))}</small></div><div class="entry-hours"><strong>${displayHours(h)}</strong><small>${euro(h*state.rate)}</small><button class="edit-inline" data-edit="${e.id}">Modifier</button></div></article>`}).join(''):'<div class="empty">Aucune heure enregistrée pour le moment.</div>';bindEditButtons()}
function formatSchedule(e){const parts=[];if(e.morningStart&&e.morningEnd)parts.push(`${e.morningStart}–${e.morningEnd}`);if(e.afternoonStart&&e.afternoonEnd)parts.push(`${e.afternoonStart}–${e.afternoonEnd}`);return parts.join(' · ')||'Horaires non renseignés'}
function renderFarms(){const totals=Object.fromEntries(state.farms.map(f=>[f.id,0]));state.entries.forEach(e=>totals[e.farmId]=(totals[e.farmId]||0)+hoursFor(e));$('#farmList').innerHTML=state.farms.map(f=>`<article class="farm-item"><span class="farm-color" style="background:${f.color}"></span><div><strong>${escapeHtml(f.name)}</strong><span>${escapeHtml(f.town||'Commune non renseignée')}</span></div><div class="farm-totals">${displayHours(totals[f.id]||0)}</div></article>`).join('')||'<div class="empty">Ajoute ta première exploitation.</div>';$('#entryFarm').innerHTML=state.farms.map(f=>`<option value="${f.id}">${escapeHtml(f.name)}</option>`).join('')}
function renderCalendar(){const y=activeMonth.getFullYear(),m=activeMonth.getMonth(),start=new Date(y,m,1),gridStart=new Date(y,m,1-((start.getDay()+6)%7));$('#calendarTitle').textContent=`${monthNames[m][0].toUpperCase()+monthNames[m].slice(1)} ${y}`;let html='';for(let i=0;i<42;i++){const d=new Date(gridStart);d.setDate(gridStart.getDate()+i);const iso=isoDate(d),has=state.entries.some(e=>e.date===iso);html+=`<button class="day ${d.getMonth()!==m?'other':''} ${iso===isoDate(new Date())?'today':''} ${has?'has-hours':''} ${iso===selectedDate?'selected':''}" data-date="${iso}">${d.getDate()}${has?'<i></i>':''}</button>`}$('#calendarGrid').innerHTML=html;$$('.day').forEach(b=>b.onclick=()=>{selectedDate=b.dataset.date;renderCalendar();renderSelectedDay()});renderSelectedDay()}
function renderSelectedDay(){const rows=state.entries.filter(e=>e.date===selectedDate),total=rows.reduce((s,e)=>s+hoursFor(e),0);$('#selectedDay').innerHTML=`<h2>${capitalize(formatDate(selectedDate))}${rows.length?` · ${displayHours(total)}`:''}</h2>${rows.length?rows.map(e=>`<div class="day-entry"><div><strong>${escapeHtml(getFarm(e.farmId).name)}</strong><p>${formatSchedule(e)}${e.notes?` · ${escapeHtml(e.notes)}`:''}</p></div><div class="entry-actions"><button data-edit="${e.id}">Modifier</button><button data-delete="${e.id}" aria-label="Supprimer">Supprimer</button></div></div>`).join(''):'<p>Aucune heure enregistrée ce jour.</p>'}`;bindEditButtons();$$('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Supprimer cette journée ?')){state.entries=state.entries.filter(e=>e.id!==b.dataset.delete);saveState();toast('Journée supprimée')}})}
function renderAll(){renderStats();renderRecent();renderFarms();renderCalendar();$('#rateInput').value=state.rate;$('#todayLabel').textContent=capitalize(new Date().toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'}))}
function navigate(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${view}View`));$$('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));scrollTo({top:0,behavior:'smooth'});if(view==='calendar')renderCalendar()}
function openEntry(date=isoDate(new Date()),entryId=null){$('#entryForm').reset();$('#entryDate').value=date;$('#breakMinutes').value=0;$('#entryFarm').value=state.farms[0]?.id||'';if(entryId){const entry=state.entries.find(e=>e.id===entryId);if(entry){$('#entryDate').value=entry.date;$('#entryFarm').value=entry.farmId;loadEntry(entry)}else loadMatchingEntry()}else loadMatchingEntry();updateEntryTotal();$('#entryDialog').showModal()}
function loadEntry(entry){editingEntryId=entry.id;$('#morningStart').value=entry.morningStart||'';$('#morningEnd').value=entry.morningEnd||'';$('#afternoonStart').value=entry.afternoonStart||'';$('#afternoonEnd').value=entry.afternoonEnd||'';$('#breakMinutes').value=entry.breakMinutes||0;$('#entryNotes').value=entry.notes||'';$('#entryMode').textContent='Continuer ma journée';$('#resumeNotice').hidden=false;$('#entrySubmit').textContent='Mettre à jour la journée'}
function loadMatchingEntry(){const match=state.entries.find(e=>e.date===$('#entryDate').value&&e.farmId===$('#entryFarm').value);if(match){loadEntry(match)}else{editingEntryId=null;$('#morningStart').value='';$('#morningEnd').value='';$('#afternoonStart').value='';$('#afternoonEnd').value='';$('#breakMinutes').value=0;$('#entryNotes').value='';$('#entryMode').textContent='Nouvelle journée';$('#resumeNotice').hidden=true;$('#entrySubmit').textContent='Enregistrer la journée'}updateEntryTotal()}
function bindEditButtons(){$$('[data-edit]').forEach(b=>b.onclick=()=>openEntry(state.entries.find(e=>e.id===b.dataset.edit)?.date||isoDate(new Date()),b.dataset.edit))}
function updateEntryTotal(){const temp={morningStart:$('#morningStart').value,morningEnd:$('#morningEnd').value,afternoonStart:$('#afternoonStart').value,afternoonEnd:$('#afternoonEnd').value,breakMinutes:$('#breakMinutes').value};$('#entryTotal').textContent=displayHours(hoursFor(temp));if(!editingEntryId)$('#entrySubmit').textContent=temp.morningStart&&temp.morningEnd&&!temp.afternoonStart&&!temp.afternoonEnd?'Enregistrer la matinée':'Enregistrer la journée'}
function changeMonth(delta){activeMonth=new Date(activeMonth.getFullYear(),activeMonth.getMonth()+delta,1);selectedDate=isoDate(activeMonth);renderAll()}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function capitalize(s){return s.charAt(0).toUpperCase()+s.slice(1)}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(t.timer);t.timer=setTimeout(()=>t.classList.remove('show'),2300)}
$$('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));$$('.nav-button').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$$('[data-open-entry]').forEach(b=>b.onclick=()=>openEntry());
$$('[data-close-dialog]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.closeDialog).close());
$('#prevMonth').onclick=$('#calPrev').onclick=()=>changeMonth(-1);$('#nextMonth').onclick=$('#calNext').onclick=()=>changeMonth(1);$('#menuButton').onclick=()=>navigate('profile');$('#addFarmButton').onclick=()=>$('#farmDialog').showModal();
['morningStart','morningEnd','afternoonStart','afternoonEnd','breakMinutes'].forEach(id=>$(`#${id}`).addEventListener('input',updateEntryTotal));
$('#entryDate').addEventListener('change',loadMatchingEntry);$('#entryFarm').addEventListener('change',loadMatchingEntry);
$('#entryForm').addEventListener('submit',e=>{e.preventDefault();if(!state.farms.length){toast('Ajoute d’abord une exploitation');return}const entry={id:editingEntryId||crypto.randomUUID(),date:$('#entryDate').value,farmId:$('#entryFarm').value,morningStart:$('#morningStart').value,morningEnd:$('#morningEnd').value,afternoonStart:$('#afternoonStart').value,afternoonEnd:$('#afternoonEnd').value,breakMinutes:Number($('#breakMinutes').value)||0,notes:$('#entryNotes').value.trim()};if(Boolean(entry.morningStart)!==Boolean(entry.morningEnd)){toast('Complète le début et la fin du matin');return}if(Boolean(entry.afternoonStart)!==Boolean(entry.afternoonEnd)){toast('Complète le début et la fin de l’après-midi');return}if(hoursFor(entry)<=0){toast('Renseigne au moins une plage horaire');return}const index=state.entries.findIndex(item=>item.id===editingEntryId);if(index>=0)state.entries[index]=entry;else state.entries.push(entry);const updated=index>=0;editingEntryId=null;selectedDate=entry.date;activeMonth=localDate(entry.date);activeMonth.setDate(1);saveState();$('#entryDialog').close();toast(updated?'Journée mise à jour':'Horaires enregistrés')});
$('#farmForm').addEventListener('submit',e=>{e.preventDefault();state.farms.push({id:crypto.randomUUID(),name:$('#farmName').value.trim(),town:$('#farmTown').value.trim(),color:$('#farmColor').value});saveState();$('#farmDialog').close();e.target.reset();toast('Exploitation ajoutée')});
$('#rateInput').onchange=()=>{state.rate=Math.max(0,Number($('#rateInput').value)||0);saveState();toast('Tarif mis à jour')};
$('#exportButton').onclick=()=>{const rows=[['Date','Exploitation','Matin début','Matin fin','Après-midi début','Après-midi fin','Pause (min)','Total heures','Montant (€)','Notes'],...state.entries.sort((a,b)=>a.date.localeCompare(b.date)).map(e=>[e.date,getFarm(e.farmId).name,e.morningStart,e.morningEnd,e.afternoonStart,e.afternoonEnd,e.breakMinutes,hoursFor(e).toFixed(2),(hoursFor(e)*state.rate).toFixed(2),e.notes])];download('\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n'),`heures-lcmc-${activeMonth.getFullYear()}-${String(activeMonth.getMonth()+1).padStart(2,'0')}.csv`,'text/csv')};
$('#backupButton').onclick=()=>download(JSON.stringify(state,null,2),`sauvegarde-lcmc-${isoDate(new Date())}.json`,'application/json');$('#restoreInput').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.entries)||!Array.isArray(data.farms))throw 0;state={...defaultState,...data};saveState();toast('Sauvegarde restaurée')}catch{toast('Fichier de sauvegarde invalide')}};
function download(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function updateNetwork(){const el=$('#networkStatus');el.textContent=navigator.onLine?'● En ligne':'● Hors ligne prêt';el.classList.toggle('online',navigator.onLine)}window.addEventListener('online',updateNetwork);window.addEventListener('offline',updateNetwork);updateNetwork();
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installButton').hidden=false});$('#installButton').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installButton').hidden=true}};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
if(document.modelContext?.registerTool){document.modelContext.registerTool({name:'add_work_entry',title:'Ajouter une journée de travail',description:'Enregistre des horaires de travail dans l’application LCMC.',inputSchema:{type:'object',properties:{date:{type:'string'},farmId:{type:'string'},morningStart:{type:'string'},morningEnd:{type:'string'},afternoonStart:{type:'string'},afternoonEnd:{type:'string'},breakMinutes:{type:'number'},notes:{type:'string'}},required:['date','farmId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const e={id:crypto.randomUUID(),morningStart:'',morningEnd:'',afternoonStart:'',afternoonEnd:'',breakMinutes:0,notes:'',...input};if(!state.farms.some(f=>f.id===e.farmId)||hoursFor(e)<=0)throw new Error('Exploitation ou horaires invalides');state.entries.push(e);saveState();return{id:e.id,totalHours:hoursFor(e)}}}).catch?.(()=>{})}
renderAll();
